import { type NextPage } from "next";
import Head from "next/head";
import { signIn, useSession } from "next-auth/react";

import { type RouterOutputs, api } from "@/utils/api";
import Image from "next/image";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage } from "@/components/loading";
import { useState } from "react";

dayjs.extend(relativeTime);

function CreatePost() {
  const { data: sessionData } = useSession();
  const { user } = sessionData!;
  const [input, setInput] = useState("");
  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      setInput("");
    },
  });

  return (
    <div className="flex gap-3 w-full">
      <Image
        src={user.image!}
        alt="Your profile picture"
        width={48}
        height={48}
        className="rounded-full"
      />
      <input
        type="text"
        value={input}
        placeholder="Type emojis"
        className=" bg-transparent grow outline-none"
        onChange={(e) => setInput(e.target.value)}
        onKeyUp={(e) => { if (e.key === "Enter") { mutate({ content: input }); } }}
        disabled={isPosting}
      />
      <button
        className=" bg-blue-400 hover:bg-blue-500 active:bg-blue-600"
        onClick={() => mutate({ content: input })}
      >
        Chirp
      </button>
    </div>
  );
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
function PostView(props: PostWithUser) {
  const { content, author, creaedAt } = props;
  const TimeFromX = dayjs(creaedAt).fromNow();

  return (
    <div className="flex  border-b border-slate-400 p-4">
      <Image
        src={author.image}
        alt={`${author.name}'s profile picture`}
        width={48}
        height={48}
        className="rounded-full mx-4"
      />
      <div className=" flex flex-col">
        <div className="flex text-gray-400 gap-1">
          <span>{`@${author.name}`}</span>
          {" "}
          ·
          <span>{TimeFromX}</span>
        </div>
        <span>{content}</span>
      </div>
    </div>
  );
}
const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();
  if (postsLoading) return <LoadingPage />;
  if (!data) return <div>No data</div>;
  return (
    <div className="flex flex-col">
      {data.map((post) => (
        <PostView {...post} key={post.id} />
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  // Start fetching
  api.posts.getAll.useQuery();

  const { data: sessionData, status } = useSession();

  if (status === "loading") return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <div className="border-b border-slate-400 p-4 flex justify-center">
            {sessionData
              ? <CreatePost />
              : <button onClick={() => void signIn()}>Sign in</button>}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
